INSERT INTO [Techniques] ([Nom]) VALUES ('Acrylique');
INSERT INTO [Techniques] ([Nom]) VALUES ('Aquarelle');
INSERT INTO [Techniques] ([Nom]) VALUES ('Dessin');
INSERT INTO [Techniques] ([Nom]) VALUES ('Huile');
INSERT INTO [Techniques] ([Nom]) VALUES ('Huile au couteau');
INSERT INTO [Techniques] ([Nom]) VALUES ('Mixte');

INSERT INTO [Sujets] ([Nom]) VALUES ('Abstrait');
INSERT INTO [Sujets] ([Nom]) VALUES ('Fleur');
INSERT INTO [Sujets] ([Nom]) VALUES ('Nature morte');
INSERT INTO [Sujets] ([Nom]) VALUES ('Paysage');
INSERT INTO [Sujets] ([Nom]) VALUES ('Portrait');

INSERT INTO [Supports] ([Nom]) VALUES ('Carton');
INSERT INTO [Supports] ([Nom]) VALUES ('Contreplaqué');
INSERT INTO [Supports] ([Nom]) VALUES ('Papier');
INSERT INTO [Supports] ([Nom]) VALUES ('Toile');

INSERT INTO [Cadres] ([Nom]) VALUES ('Aucun');
INSERT INTO [Cadres] ([Nom]) VALUES ('Américain');
INSERT INTO [Cadres] ([Nom]) VALUES ('Encadré');
INSERT INTO [Cadres] ([Nom]) VALUES ('Sous-verre');

INSERT INTO [Stockages] ([Nom]) VALUES ('Atelier');
INSERT INTO [Stockages] ([Nom]) VALUES ('Carton atelier');
INSERT INTO [Stockages] ([Nom]) VALUES ('Carton Ch. Bas');
INSERT INTO [Stockages] ([Nom]) VALUES ('Cheminée');
INSERT INTO [Stockages] ([Nom]) VALUES ('Couloir');
INSERT INTO [Stockages] ([Nom]) VALUES ('Cuisine');
INSERT INTO [Stockages] ([Nom]) VALUES ('Devant table carrée');
INSERT INTO [Stockages] ([Nom]) VALUES ('Mur atelier');
INSERT INTO [Stockages] ([Nom]) VALUES ('Mur bureau');
INSERT INTO [Stockages] ([Nom]) VALUES ('Mur fond atelier');
INSERT INTO [Stockages] ([Nom]) VALUES ('Mur salon');
INSERT INTO [Stockages] ([Nom]) VALUES ('Pendu armoire');
INSERT INTO [Stockages] ([Nom]) VALUES ('Pendu atelier');
INSERT INTO [Stockages] ([Nom]) VALUES ('Salon');
INSERT INTO [Stockages] ([Nom]) VALUES ('Sur table carrée');

INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('10 x 10', 1);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('13 x 18', 1);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('18 x 24', 2);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('19 x 19', 2);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('19 x 27', 3);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('20 x 20', 2);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('20 x 28', 3);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('21 x 30', 3);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('22 x 27', 3);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('24 x 30', 4);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('28 x 39', 6);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('30 x 21', 3);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('30 x 24', 4);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('30 x 30', 5);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('30 x 40', 6);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('36 x 26', 5);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('37 x 20', 5);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('37 x 32', 6);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('38 x 46', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('38 x 54', 10);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('40 x 30', 6);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('40 x 40', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('40 x 50', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('41 x 33', 6);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('43 x 20', 5);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('44 x 32,5', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('46 x 38', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('50 x 32,5', 8);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('50 x 50', 10);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('50 x 61', 12);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('50 x 70', 20);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('54 x 46', 10);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('54 x 65', 15);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('60 x 60', 15);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('61 x 46', 12);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('61 x 50', 12);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('65 x 54', 15);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('70 x 50', 20);
INSERT INTO [Tailles] ([Nom], [Valeur]) VALUES ('80 x 60', 25);

INSERT INTO [Cotes] ([Nom], [Valeur]) VALUES ('Officielle', 20);
INSERT INTO [Cotes] ([Nom], [Valeur]) VALUES ('Expo', 20);
INSERT INTO [Cotes] ([Nom], [Valeur]) VALUES ('Amis', 15);

// ALTER TABLE [Tableaux] ALTER COLUMN [Tableau_ID] IDENTITY (1, 1);
